version: '3.4'

services:
  monitoring.api:
    image: ${DOCKER_REGISTRY-}monitoringapi
    build:
      context: .
      dockerfile: Monitoring.Api/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:443;http://+80
    ports:
        - 8082:80
        - 8084:443
  grafana:
    container_name: grafana
    image: grafana/grafana:master
    ports:
        - 3000:3000
    volumes: 
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
  prometheus:
    image: prom/prometheus
    container_name: prometheus_grafprom
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    ports:
      - 9090:9090
  alertmanager:
     image: prom/alertmanager:latest
     container_name: alertmanager
     volumes:
       - ./alertmanager:/etc/alertmanager
     command:
       - '--config.file=/etc/alertmanager/alertmmanager.yml'
       - '--storage.path=/alertmanager'
     ports:
       - '9093:9093'